### ISSUE TITLE
Ещё позавчера в Tags был один релиз. Почему вчера его удалили

### ISSUE THREAD

**Issue by Artem13327** [openvk/mobile-android-refresh#2]

**Comment by tretdm** [comment]
Потому что удаленный тег был тогда с [последним коммитом](https://github.com/openvk/mobile-android-refresh/commit/4b89031c932c5befabe36763cc38813b4c5143e9) - это версия 0.0.9.alpha, а APK-файлы были из 0.0.1-alpha. Подвох в том, что к [коммиту 0.0.1-alpha](https://github.com/openvk/mobile-android-refresh/commit/f9aabe581cd079025b8b6033df524fd6103138fb)) уже вряд ли можно добавить тег, поэтому я оставил ниже ссылку на ранние версии.

![изображение](https://user-images.githubusercontent.com/76806170/217247388-84bb1ace-03fa-4bd8-bbef-122923634f84.png)
