### ISSUE TITLE
Открытие группы/профиля только с уже запущенного приложения

### ISSUE THREAD

**Issue by Artem13327** [openvk/mobile-android-refresh#5]
У меня два клиента OpenVK и если попытаться открыть группу через меню группы, зачем-то спрашивает открыть через какой клиент открыть
Этот-же Issues только для Legacy [openvk/mobile-android-legacy/issues/97](https://github.com/openvk/mobile-android-legacy/issues/97)

**Comment by tretdm** [comment]
Исправлено в коммите [bf7fa42](https://github.com/openvk/mobile-android-refresh/commit/bf7fa4210c908dc0200ebbff427c57a332075fc8). В приложении OpenVK Legacy для Android исправление появится позже.
