### ISSUE TITLE
Меню в профиле как в Legacy

### ISSUE THREAD

**Issue by Artem13327** [openvk/mobile-android-refresh#6]
Я об этом
![Screenshot](https://user-images.githubusercontent.com/68551925/218722548-c1498bf9-fceb-4f83-b072-49bb6d0d558d.png)

**Comment by tretdm** [comment]
Про дизайн прошу ознакомиться https://m2.material.io/components/menus. А что насчет содержимого в пунктах - дойдем и до него.

**Comment by tretdm** [comment]
Добавлено в коммите 9b111d1
